#!/bin/bash
set -e

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS \`${TENANT1_DB_NAME}\`;
    CREATE USER IF NOT EXISTS '${TENANT1_DB_USER}'@'%' IDENTIFIED BY '${TENANT1_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${TENANT1_DB_NAME}\`.* TO '${TENANT1_DB_USER}'@'%';

    CREATE DATABASE IF NOT EXISTS \`${TENANT2_DB_NAME}\`;
    CREATE USER IF NOT EXISTS '${TENANT2_DB_USER}'@'%' IDENTIFIED BY '${TENANT2_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON \`${TENANT2_DB_NAME}\`.* TO '${TENANT2_DB_USER}'@'%';

    FLUSH PRIVILEGES;
EOSQL
